
name: Running Tests

on:
  push:
    branches: [ main ]

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js 16.13.1
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Set up database
        run: npx prisma db push --preview-feature
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

      - name: Run tests
        run: npm run test:e2e
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres